version: '3'
services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway:
    build: 
      context: ./ventura-client-gateway
      dockerfile: dockerfile.prod
    image: ventura-client-gateway-production
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    build: 
      context: ./ventura-auth
      dockerfile: dockerfile.prod
    image: ventura-auth-production
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222

  ventura-ui:
    build: 
      context: ./ventura-ui
      dockerfile: dockerfile.prod
    ports:
      - "${VENTURA_UI_PORT}:${VENTURA_UI_PORT}"
    image: ventura-ui-production
    volumes:
      - ./ventura-ui/src:/usr/src/app/src
    command: npm run start
    environment:
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}	
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_SIGN_IN_FORCE_REDIRECT_URL=${CLERK_SIGN_IN_FORCE_REDIRECT_URL}
      - CLERK_SIGN_UP_FORCE_REDIRECT_URL=${CLERK_SIGN_UP_FORCE_REDIRECT_URL}
      - CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=${CLERK_SIGN_IN_FALLBACK_REDIRECT_URL}
      - CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=${CLERK_SIGN_UP_FALLBACK_REDIRECT_URL}
    restart: unless-stopped