version: '3'
services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway-dev:
    build: 
      context: ./ventura-client-gateway
      target: development
    ports:
      - "${CLIENT_GATEWAY_PORT}:3001"
    volumes:
      - ./ventura-client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms-dev:
    build: 
      context: ./ventura-auth
      target: development
    volumes:
      - ./ventura-auth/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222

  ventura-ui-dev:
    build: 
      context: ./ventura-ui
    ports:
      - "${VENTURA_UI_PORT}:3000"
    volumes:
      - ./ventura-ui/src:/usr/src/app/src
    command: npm run dev
    environment:
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}	
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_SIGN_IN_FORCE_REDIRECT_URL=${CLERK_SIGN_IN_FORCE_REDIRECT_URL}
      - CLERK_SIGN_UP_FORCE_REDIRECT_URL=${CLERK_SIGN_UP_FORCE_REDIRECT_URL}
      - CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=${CLERK_SIGN_IN_FALLBACK_REDIRECT_URL}
      - CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=${CLERK_SIGN_UP_FALLBACK_REDIRECT_URL}
    restart: unless-stopped