version: '3'
services:
  nats-server:
    container_name: nats-server-dev
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway-dev:
    container_name: client-gateway-dev
    build: 
      context: ./ventura-client-gateway
      target: development
    ports:
      - "${CLIENT_GATEWAY_PORT}:8080"
    volumes:
      - ./ventura-client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=8080
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms-dev:
    container_name: auth-ms-dev
    build: 
      context: ./ventura-auth
      target: development
    volumes:
      - ./ventura-auth/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${DATABASE_URL}